// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOPEG4eC6uSwHcpXM6m7WMFzIi7DxerFY',
    appId: '1:503957353721:web:f1f46c2ac19c98ac4d9e28',
    messagingSenderId: '503957353721',
    projectId: 'inventory-app-giadagiacobbe',
    authDomain: 'inventory-app-giadagiacobbe.firebaseapp.com',
    storageBucket: 'inventory-app-giadagiacobbe.firebasestorage.app',
    measurementId: 'G-68SQD6EE3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa7QtrgpN5it1LxrlzUxkcIaFevLlIJQ4',
    appId: '1:503957353721:android:7bcf631f063956e54d9e28',
    messagingSenderId: '503957353721',
    projectId: 'inventory-app-giadagiacobbe',
    storageBucket: 'inventory-app-giadagiacobbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB96seGSWIpyCEaE3V8eRRFyIndbiBbPtY',
    appId: '1:503957353721:ios:0495f1a2460eca4c4d9e28',
    messagingSenderId: '503957353721',
    projectId: 'inventory-app-giadagiacobbe',
    storageBucket: 'inventory-app-giadagiacobbe.firebasestorage.app',
    iosBundleId: 'com.example.inclass15',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB96seGSWIpyCEaE3V8eRRFyIndbiBbPtY',
    appId: '1:503957353721:ios:0495f1a2460eca4c4d9e28',
    messagingSenderId: '503957353721',
    projectId: 'inventory-app-giadagiacobbe',
    storageBucket: 'inventory-app-giadagiacobbe.firebasestorage.app',
    iosBundleId: 'com.example.inclass15',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOPEG4eC6uSwHcpXM6m7WMFzIi7DxerFY',
    appId: '1:503957353721:web:0d23e024216cf0444d9e28',
    messagingSenderId: '503957353721',
    projectId: 'inventory-app-giadagiacobbe',
    authDomain: 'inventory-app-giadagiacobbe.firebaseapp.com',
    storageBucket: 'inventory-app-giadagiacobbe.firebasestorage.app',
    measurementId: 'G-M1CET1ZXHX',
  );
}
